### ISSUE TITLE
部分接口未适配，详情见描述

### ISSUE THREAD

**Issue by Gyzztzj** [react-native-oh-library/react-native-keyboard-aware-scroll-view#2]
### 描述 / Description

1. 属性viewIsInsideTabBar在iOS中支持，HarmonyOS不支持；属性描述：添加表示TabBarIOS高度的额外偏移量。
2. 属性keyboardOpeningTime在iOS中支持，HarmonyOS不支持；属性描述：设置滚动到新位置前的延迟时间，默认为250。
3. 方法onKeyboardWillShow在iOS中支持，HarmonyOS不支持；方法描述：虚拟键盘将要显示时触发事件。
4.方法onKeyboardWillHide在iOS中支持，HarmonyOS不支持；方法描述：虚拟键盘将要隐藏时触发事件。
5. 方法onKeyboardWillChangeFrame在iOS中支持，HarmonyOS不支持；方法描述：当键盘状态即将改变时触发事件。
6. 方法onKeyboardDidChangeFrame在iOS中支持，HarmonyOS不支持；方法描述：当键盘状态已经改变时触发事件。
7. 方法scrollIntoView在iOS中支持，HarmonyOS不支持；方法描述：将组件中的元素滚动到视图中。

### 库版本 / Library version

0.9.5-0.0.1

### React Native OpenHarmony version

0.72.27

### 构建类型 / Build type

None

### 设备 / Device

None

### 已悉知 / Acknowledgements

Yes

**Comment by hanhuigui** [comment]
已有issue
